### ISSUE TITLE
当前vector map等 不支持struct传入，映射到lua嘛

### ISSUE THREAD

**Issue by husanpao** [xiyoo0812/luakit#2]
1.  尝试了map，array，vector 等都不支持映射自定义struct哦。都是直接lua_pushnil了？这个能支持嘛？判断类型到struct然后createtable解决这个？

**Comment by husanpao** [comment]
但是用了折中的方法可以解决了，就是先将struct 转为new_table然后再加入map，vector等容器既可以用

**Comment by xiyoo0812** [comment]
> 但是用了折中的方法可以解决了，就是先将struct 转为new_table然后再加入map，vector等容器既可以用

C++传递 基于自定义struct的容器给lua吗？这种建议先将struct注册成class就可以在容器中使用

**Comment by husanpao** [comment]
> > 但是用了折中的方法可以解决了，就是先将struct 转为new_table然后再加入map，vector等容器既可以用
> 
> C++传递 基于自定义struct的容器给lua吗？这种建议先将struct注册成class就可以在容器中使用

好的，待会使用看一下。谢谢您的解答

**Comment by husanpao** [comment]
## 这种注册是不行的,或许是我的写法错了
```
c++:

struct Event {
    Label weight;
    float hold;
    int event;
    int left;
    int right;
    int top;
    int bottom;
};
struct Label {
    string name;
    bool render;
    string text;
    float threshold;
    bool flag;
};

 kit_state.new_class<Label>(
            "name", &Label::name,
            "render", &Label::render,
            "text", &Label::text,
            "threshold", &Label::threshold,
            "flag", &Label::flag
    );
    kit_state.new_class<Event>(
            "weight", &Event::weight,
            "hold", &Event::hold,
            "event", &Event::event,
            "left", &Event::left,
            "right", &Event::right,
            "top", &Event::top,
            "bottom", &Event::bottom
    );
    Label l = {"name", false, "text", 1, false};
    Event e = {l, 1, 1, 1, 1, 1, 1};
    kit_state.set("testEvent", e);
    kit_state.table_call("Plugin", "Test");


lua:
function Plugin:Test()
    print(testEvent.event)
    print(testEvent.weight.name)
end
```

## 这种使用是ok的
```
c++:

class LabelClass {
public:
    string name;
    bool render;
    string text;
    float threshold;
    bool flag;
};

class EventClass {
public:
    LabelClass *weight;
    float hold;
    int event;
    int left;
    int right;
    int top;
    int bottom;
};

kit_state.new_class<LabelClass>(
            "name", &LabelClass::name,
            "render", &LabelClass::render,
            "text", &LabelClass::text,
            "threshold", &LabelClass::threshold,
            "flag", &LabelClass::flag
    );
    kit_state.new_class<EventClass>(
            "weight", &EventClass::weight,
            "hold", &EventClass::hold,
            "event", &EventClass::event,
            "left", &EventClass::left,
            "right", &EventClass::right,
            "top", &EventClass::top,
            "bottom", &EventClass::bottom
    );
    LabelClass *l = new LabelClass();
    l->name = "name";
    l->threshold = 1;
    l->render = false;
    l->text = "text";
    l->flag = true;
    auto e = new EventClass();
    e->hold = 1;
    e->bottom = 1;
    e->event = 1;
    e->weight = l;
    e->top = 1;
    e->left = 1;
    e->right = 1;
    kit_state.set("testEvent", e);
    kit_state.table_call("Plugin", "Test");

lua:
function Plugin:Test()
    print(testEvent.event)
    print(testEvent.weight.name)
end

```
这种注册是可以使用的

**Comment by xiyoo0812** [comment]
> ## 这种注册是不行的,或许是我的写法错了
> ```
> c++:
> 
> struct Event {
>     Label weight;
>     float hold;
>     int event;
>     int left;
>     int right;
>     int top;
>     int bottom;
> };
> struct Label {
>     string name;
>     bool render;
>     string text;
>     float threshold;
>     bool flag;
> };
> 
>  kit_state.new_class<Label>(
>             "name", &Label::name,
>             "render", &Label::render,
>             "text", &Label::text,
>             "threshold", &Label::threshold,
>             "flag", &Label::flag
>     );
>     kit_state.new_class<Event>(
>             "weight", &Event::weight,
>             "hold", &Event::hold,
>             "event", &Event::event,
>             "left", &Event::left,
>             "right", &Event::right,
>             "top", &Event::top,
>             "bottom", &Event::bottom
>     );
>     Label l = {"name", false, "text", 1, false};
>     Event e = {l, 1, 1, 1, 1, 1, 1};
>     kit_state.set("testEvent", e);
>     kit_state.table_call("Plugin", "Test");
> 
> 
> lua:
> function Plugin:Test()
>     print(testEvent.event)
>     print(testEvent.weight.name)
> end
> ```
> 
> ## 这种使用是ok的
> ```
> c++:
> 
> class LabelClass {
> public:
>     string name;
>     bool render;
>     string text;
>     float threshold;
>     bool flag;
> };
> 
> class EventClass {
> public:
>     LabelClass *weight;
>     float hold;
>     int event;
>     int left;
>     int right;
>     int top;
>     int bottom;
> };
> 
> kit_state.new_class<LabelClass>(
>             "name", &LabelClass::name,
>             "render", &LabelClass::render,
>             "text", &LabelClass::text,
>             "threshold", &LabelClass::threshold,
>             "flag", &LabelClass::flag
>     );
>     kit_state.new_class<EventClass>(
>             "weight", &EventClass::weight,
>             "hold", &EventClass::hold,
>             "event", &EventClass::event,
>             "left", &EventClass::left,
>             "right", &EventClass::right,
>             "top", &EventClass::top,
>             "bottom", &EventClass::bottom
>     );
>     LabelClass *l = new LabelClass();
>     l->name = "name";
>     l->threshold = 1;
>     l->render = false;
>     l->text = "text";
>     l->flag = true;
>     auto e = new EventClass();
>     e->hold = 1;
>     e->bottom = 1;
>     e->event = 1;
>     e->weight = l;
>     e->top = 1;
>     e->left = 1;
>     e->right = 1;
>     kit_state.set("testEvent", e);
>     kit_state.table_call("Plugin", "Test");
> 
> lua:
> function Plugin:Test()
>     print(testEvent.event)
>     print(testEvent.weight.name)
> end
> ```
> 
> 这种注册是可以使用的

可能是有些成员判定的模板问题，我抽时间测试下
